#+author: Daniel Rothblatt
#+creator: Emacs 27.1 (Org mode 9.4.4 + ox-hugo)
#+hugo_front_matter_format: toml
#+hugo_level_offset: 1
#+hugo_base_dir: ~/blog
#+hugo_section: posts
#+hugo_date_format: %Y-%m-%dT%T%z
#+hugo_weight: auto
#+options: ':nil -:nil ^:{} num:nil toc:nil
#+TODO: PLANNING STARTED EDITING | RELEASED
* Cities                                                    :URBANISM:CITIES:
** Transportation                                                   :TRANSPORTATION:
*** Cars                                                               :CARS:
**** Why 
*** Bikes                                                             :BIKES:
*** Public Transit                                                  :TRANSIT:
**** The Subway                                                 :SUBWAY:RAIL:
**** The Bus                                                            :BUS:
*** Theory                                                           :THEORY:
**** What is Transportation, Anyway?
     :PROPERTIES:
     :EXPORT_FILE_NAME: what-is-transportation
     :EXPORT_DATE: <2021-02-21 Sun>
     :END:

     Every day[fn:1], billions of people wake up in one place, attend
     to whatever tasks make up their morning, and leave for another
     place. That place may be their job, their school, a store or
     restaurant, a park, someone else's home, or any number of
     other destinations. They get where they're going in any number of
     ways: on foot or in a wheelchair; by bike, scooter, or moped;
     aboard trains, trams, buses, and ferries; in a car, driven either
     by themselves or by someone else. A few hours later, they return
     home, either the same way they left or a different way. They may
     make some number of stops along the way to their daily
     destinations: They may stop at a friend's home or meet friends in
     a public place; they may buy ingredients or prepared food for a
     meal; they may go to a club for karaoke; or maybe they go
     straight home, eager to change clothes and recover from their
     day.

     This all sounds unremarkable to most of us, even a little boring.
     "Big whoop," you may say. "Who cares?" you may ask. But have you
     ever asked why we bother with all of this? Every day billions of
     people make billions of little round-trip journeys out into the
     world. Those trips make up a significant part of most people's
     lives. We all occupy ourselves in /transportation/ sometimes. So,
     as [[https://gothamist.com/arts-entertainment/thanks-mta-for-the-depressing-af-poem-thats-been-in-this-subway-tunnel-since-the-90s][the famously depressing poem at Times Square asks]], why bother?
***** What is transportation about?

      We get our first hint from the way we talked about
      transportation above. You wake up in the morning, go somewhere
      else, do something in that other place, and return home later.
      What can we conclude from this? Well, a couple of things come to
      mind:

      1. You have things to do.
      2. You can't do all of them at home, so you have to go somewhere
         else.


      "You have things to do" is intentionally vague. Your whole life
      is having things to do! So now we can informally define
      transportation:

      #+begin_verse
      Transportation is anything that helps you get to the places where you live your life.
      #+end_verse

      We all have different goals, desires, obligations, and
      relationships, and we can't colocate all of them in the same
      place. *So transportation is about us!* It's about living your
      life the way you want to live it.
***** What is the goal of a transportation system?

      Because each of us has our own places to go and things to do, we
      rely on /transportation systems/ that can get us where we're
      going. There are infinite possible reasons you're making a trip,
      and countless possible trips to make, but the system doesn't
      need to know anything about those. Whoever you are and whatever
      you're doing, it helps you get where you need to go when you
      need to go there.

      Notice that so far I haven't said anything about the /mode/ of
      transportation.[fn:3] Nor have I said anything about how to lay
      out streets or roads.[fn:4] A transportation system is *not*
      successful because it specifically moves cars, bikes, buses,
      trains, or anything else. It doesn't succeed because streets are
      built on a grid, or not on a grid, or on a grid in *some* spots
      but not in others.[fn:5] A transportation system *is* successful
      when it moves people. A transportation system is successful when
      it makes it easy for its users to live their lives. All the rest
      is commentary.

* Personal                                                         :PERSONAL:
** RELEASED BS''D, or Getting Started                  :JUDAISM:META:WRITING:
   CLOSED: [2021-02-21 Sun 11:46]
   :PROPERTIES:
   :EXPORT_FILE_NAME: besiyata-dishmaya
   :EXPORT_DATE: <2021-02-21 Sun>
   :END:

   Many Jews write [[https://en.wikipedia.org/wiki/Besiyata_Dishmaya][בס״ד‎]][fn:6], meaning "with the help of Heaven", at the top
   of a written document, a reminder that all things come from G-d.
   It's not a request for help, but a reminder that help is given. It
   feels appropriate for me to follow this tradition in naming my
   first blog post for two reasons:

   1. I've never written a blog before and have, honestly, only half
      an idea what I'm doing. I don't think I need to request help
      from a higher power to write this little blog, but it's helpful
      to remember that help is given regardless.
   2. Nothing is harder to write on than a blank page. I've been
      thinking about starting a blog for a while, but had no idea
      where to start. I might as well just put something—anything—on
      the page and get going, else I may never start.


   Now I've got writing on the page. The blog has begun. There's a lot
   to write about, so let's get started!
* Computers                                                       :COMPUTERS:
** Emacs                                                              :EMACS:

* Footnotes

[fn:1] Before[fn:2] the COVID-19 pandemic, of course

[fn:2] And hopefully after!

[fn:3] And I won't! Not here!

[fn:4] Too important to ignore and too important to even try to write
about here.

[fn:5] Looking at you, Manhattan!

[fn:6] The full phrase in Aramaic: בְּסִיַּיעְתָּא דִשְׁמַיָּא (transcription: besiyata dishmaya)
