#+author: Daniel Rothblatt
#+creator: Emacs 27.1 (Org mode 9.4.4 + ox-hugo)
#+hugo_front_matter_format: toml
#+hugo_level_offset: 1
#+hugo_base_dir: ~/blog
#+hugo_section: posts
#+hugo_date_format: %Y-%m-%dT%T%z
#+hugo_weight: auto
#+options: ':nil -:nil ^:{} num:nil toc:nil
#+TODO: PLANNING STARTED EDITING | RELEASED
* Cities                                                    :URBANISM:CITIES:
** Transportation                                                   :TRANSPORTATION:
*** Cars                                                               :CARS:
*** Bikes                                                             :BIKES:
*** Public Transit                                                  :TRANSIT:
**** The Subway                                                 :SUBWAY:RAIL:
**** The Bus                                                            :BUS:
*** Theory                                                           :THEORY:
**** What is Transportation, Anyway?
     :PROPERTIES:
     :EXPORT_FILE_NAME: what-is-transportation
     :EXPORT_DATE: <2021-02-21 Sun 16:00>
     :END:

     #+begin_description
     What moves you?
     #+end_description

     Every day[fn:1], billions of people wake up in one place, attend
     to whatever tasks make up their morning, and leave for another
     place. That place may be their job, their school, a store or
     restaurant, a park, someone else's home, or any number of
     other destinations. They get where they're going in any number of
     ways: on foot or in a wheelchair; by bike, scooter, or moped;
     aboard trains, trams, buses, and ferries; in a car, driven either
     by themselves or by someone else. A few hours later, they return
     home, either the same way they left or a different way. They may
     make some number of stops along the way to their daily
     destinations: They may stop at a friend's home or meet friends in
     a public place; they may buy ingredients or prepared food for a
     meal; they may go to a club for karaoke; or maybe they go
     straight home, eager to change clothes and recover from their
     day.

     This all sounds unremarkable to most of us, even a little boring.
     "Big whoop," you may say. "Who cares?" you may ask. But have you
     ever asked why we bother with all of this? Every day billions of
     people make billions of little round-trip journeys out into the
     world. Those trips make up a significant part of most people's
     lives. We all occupy ourselves in /transportation/ sometimes. So,
     as [[https://gothamist.com/arts-entertainment/thanks-mta-for-the-depressing-af-poem-thats-been-in-this-subway-tunnel-since-the-90s][the famously depressing poem at Times Square asks]], why bother?
***** What is transportation about?

      We get our first hint from the way we talked about
      transportation above. You wake up in the morning, go somewhere
      else, do something in that other place, and return home later.
      What can we conclude from this? Well, a couple of things come to
      mind:

      1. You have things to do.
      2. You can't do all of them at home, so you have to go somewhere
         else.


      "You have things to do" is intentionally vague. Your whole life
      is having things to do! So now we can informally define
      transportation:

      #+begin_verse
      Transportation is anything that helps you get to the places where you live your life.
      #+end_verse

      We all have different goals, desires, obligations, and
      relationships, and we can't colocate all of them in the same
      place. *So transportation is about us!* It's about living your
      life the way you want to live it.
***** What is the goal of a transportation system?

      Because each of us has our own places to go and things to do, we
      rely on /transportation systems/ that can get us where we're
      going. There are infinite possible reasons you're making a trip,
      and countless possible trips to make, but the system doesn't
      need to know anything about those. Whoever you are and whatever
      you're doing, it helps you get where you need to go when you
      need to go there.

      Notice that so far I haven't said anything about the /mode/ of
      transportation.[fn:3] Nor have I said anything about how to lay
      out streets or roads.[fn:4] A transportation system is *not*
      successful because it specifically moves cars, bikes, buses,
      trains, or anything else. It doesn't succeed because streets are
      built on a grid, or not on a grid, or on a grid in *some* spots
      but not in others.[fn:5] A transportation system *is* successful
      when it moves people. A transportation system is successful when
      it makes it easy for its users to live their lives. All the rest
      is commentary.

**** Induced Demand                              :INDUCED_DEMAND:OUR_STREETS:
***** One More Lane Won't Fix It                                       :CARS:
      :PROPERTIES:
      :EXPORT_FILE_NAME: no-more-lanes
      :EXPORT_DATE: <2021-02-22 Mon>
      :END:

      #+begin_description
      The contractually-obligated induced demand post!
      #+end_description

      You're driving on your town's Main Street, heading up to the
      bowling alley.[fn:6] But what's this? A traffic jam! How
      aggravating, you shout! This is because Main Street just isn't
      wide enough, you decide. One More Lane Will Fix It!™

      Does this sound familiar? If you're American, you've probably
      seen at least one road widening near you in your life, most
      likely in an attempt to alleviate congestion. If you've been
      around long enough, you've probably seen the same road widened
      more than once! But there's still traffic! And that leads to the
      big question:

      #+begin_quote
      If adding lanes to the road fixed traffic, why would we have to
      do it more than once?
      #+end_quote

      And here's the big answer we're working towards:

      #+begin_quote
      It doesn't.
      #+end_quote

      In fact, adding lanes can make traffic worse. To find out why,
      let's explore [[https://www.strongtowns.org/journal/tag/induced+demand][the]] [[https://www.theurbanist.org/2019/11/12/the-law-of-induced-demand-road-widening-and-i-976-invites-congestion/][oft]]-[[https://www.vox.com/videos/22280067/highways-traffic-worse-congestion-expansion][explained]] [[https://www.bloomberg.com/news/articles/2018-09-06/traffic-jam-blame-induced-demand][concept]] [[https://usa.streetsblog.org/category/induced-demand/][of]] [[https://en.wikipedia.org/wiki/Induced_demand][induced demand]]!
****** What induced demand is

       Induced demand is the phenomenon in economics that demand
       increases with the supply of certain goods. A
       non-transportation example is electricity usage: The more the
       supply increases (and the price drops), the more electricity
       you use. If you could only afford one lightbulb per room in
       your house and your electric bill drops in half after the
       opening of a new power plant,[fn:7] you're likely to get a
       second bulb for each room. Demand has risen to meet supply.
       There are two related phenomena that make up induced demand:
       *latent demand* and *generated demand*.
******* <<<Latent demand>>>

        If you always wanted more lightbulbs in your house because you
        felt like it was too dark, but you couldn't afford the
        electricity until the supply increased, that's *latent demand*.
        The demand existed but couldn't be met by the supply until the
        supply increased. The increased supply has *revealed*
        additional existing demand.
******* <<<Generated demand>>>

        But if you didn't have enough lightbulbs before, what did you
        do instead? Maybe you didn't want more bulbs; instead, you lit
        candles or spent more time at a friend's house with more
        light. You found ways around the lack of light, but now that
        you can afford more lights, you want them. That's *generated
        demand*. The increased supply has *created* additional demand.
****** Induced demand on the road

       Now back to Main Street. Let's say enough people complain about
       the traffic[fn:8] and your town adds a lane to Main Street.
       When we approach automobiles with induced demand in our
       toolkit, we can see why this is a mistake and explain why
       adding lanes doesn't fix traffic. When you add space to the
       road, you're both revealing latent demand and generating new
       demand, and within a short amount of time, the new road space
       is filled. If anything, the traffic will get worse! Here's why:
******* Latent demand on the road

        Sure, you were driving on Main Street when it had only two
        lanes, but the traffic was keeping a lot of other people off
        the road—there's only so much space for cars,[fn:9] and more
        people wanted to drive than were able to. Now that we've added
        a lane and congestion has improved, though, many of those
        drivers will see room for new drivers that they can fill.
        Through this lens of latent demand we can see a mistaken
        assumption that we were making:

        #+begin_quote
        Adding a lane to fix traffic assumes that the number of
        drivers on the road (i.e., the demand for driving on that
        road) will remain constant after adding the lane.
        #+end_quote

        But that wasn't right at all, we see: After increasing the
        supply of road space, we end up meeting some of this latent
        demand. Within months, congestion is just as bad as it was
        before. But maybe it's even worse!
******* Generated demand on the road

        Through all the traffic on Main Street, you have to imagine
        there were some people in your town who simply opted out of
        it. If they wanted to go to the bowling alley, maybe they
        drove at a different time,[fn:10] or maybe they walked
        instead,[fn:11] or maybe they never made the trip at
        all.[fn:12]

        But now that there's a new lane on Main Street, some of the
        drivers who chose to wait will leave at the same time as
        everyone else, and new drivers are added to Main Street. After
        all, /there's so much more space now!/ And some of the people
        who just stayed home decide that they want a piece of the
        action too! They start driving to the bowling alley, and new
        drivers are added to Main Street. And we haven't talked about
        the *opportunity cost* of widening Main Street. Maybe the people
        who used to walk to the bowling alley can't do that safely any
        more.[fn:13] Now some of them are swept up in the automotive
        arms race too, and new drivers are added to Main Street.
        Through this lens of generated demand we can see some more
        mistaken assumptions we were making:

        #+begin_quote
        Adding a lane to fix traffic assumes:

        - that all drivers want to or should use the road during peak
          hours, when congestion is worst, when in reality, drivers
          may use the road during off-peak times instead;
        - that enabling more car trips makes everyone better off, when
          there are plenty of people who were perfectly happy not
          making those trips at all;
        - and that the goal of transportation planning is to move
          *cars* rather than *people*, and therefore enabling more
          cars to use the road improves the system for everyone.
        #+end_quote

        So we may be even worse off than we were before: We've
        summoned a horde of new cars to Main Street, and within a few
        months, not only has congestion not improved, but it may have
        gotten *worse!* Induced demand strikes again!
****** What should we do instead?

       So, to recap, we've seen that increasing road space induces
       demand for road space, both by revealing latent demand and by
       creating generated demand. In other words, adding lanes is
       solving traffic with traffic.

       Let's take a step back now and ask what problem we were trying
       to solve in the first place. Since [[What is the goal of a transportation system?][transportation is about
       helping people live their lives,]] and being stuck in traffic
       certainly doesn't seem like a great way to live a life, we do
       genuinely want to reduce congestion. But if adding space to our
       roads just puts more people in cars and doesn't solve
       congestion, it's counterproductive to do that. But what if we
       go in the *other* direction? If *adding* car space to the road
       doesn't fix congestion, maybe *subtracting* it will. More on
       that to come!
* Personal                                                         :PERSONAL:
** RELEASED BS''D                                      :JUDAISM:META:WRITING:
   CLOSED: [2021-02-21 Sun 11:46]
   :PROPERTIES:
   :EXPORT_FILE_NAME: besiyata-dishmaya
   :EXPORT_DATE: <2021-02-21 Sun 12:00>
   :END:

   #+begin_description
   Getting started is the hardest part.
   #+end_description

   Many Jews write [[https://en.wikipedia.org/wiki/Besiyata_Dishmaya][בס״ד‎]][fn:14], meaning "with the help of Heaven", at the top
   of a written document, a reminder that all things come from G-d.
   It's not a request for help, but a reminder that help is given. It
   feels appropriate for me to follow this tradition in naming my
   first blog post for two reasons:

   1. I've never written a blog before and have, honestly, only half
      an idea what I'm doing. I don't think I need to request help
      from a higher power to write this little blog, but it's helpful
      to remember that help is given regardless.
   2. Nothing is harder to write on than a blank page. I've been
      thinking about starting a blog for a while, but had no idea
      where to start. I might as well just put something—anything—on
      the page and get going, else I may never start.


   Now I've got writing on the page. The blog has begun. There's a lot
   to write about, so let's get started!
* Computers                                                       :COMPUTERS:
** Emacs                                                              :EMACS:

* Footnotes

[fn:1] Before[fn:2] the COVID-19 pandemic, of course.

[fn:2] And hopefully after!

[fn:3] And I won't! Not here!

[fn:4] Too important to ignore and too important to even try to write
about here.

[fn:5] Looking at you, Manhattan!

[fn:6] Sure, [[https://en.wikipedia.org/wiki/Bowling_Alone][Bowling Alone]] is sad, but you're in the mood for some
curly fries.

[fn:7] Or after solar panels get installed on your roof.

[fn:8] I wonder if everyone else was trying to get their bowling
alley curly fries fix too…

[fn:9] This is basically what traffic congestion is: Too many cars
sharing a limited amount of space.

[fn:10] The curly fries can wait.

[fn:11] Ain't nothing getting between me and those curly fries!

[fn:12] Maybe I shouldn't be eating my weight in bowling alley
curly fries once a week anyway…

[fn:13] One thing American urban planning has done wrong in many
places is ignore sidewalks. Wide roads are often built with no place
for non-drivers on them; you can probably think of examples you're
familiar with.

[fn:14] The full phrase in Aramaic: בְּסִיַּיעְתָּא דִשְׁמַיָּא (transcription: besiyata dishmaya)

[fn:15] More on this another day!
